// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLc8tVUsPip6nAZNOrSAFcedHot7YA3K8',
    appId: '1:481115480812:web:9613308e0b3652bb997bc9',
    messagingSenderId: '481115480812',
    projectId: 'mycotes',
    authDomain: 'mycotes.firebaseapp.com',
    storageBucket: 'mycotes.appspot.com',
    measurementId: 'G-NNGW2X77QK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqe49oOE5e2A_2NbicNYCMPog19INKvgc',
    appId: '1:481115480812:android:71372e824c0148b7997bc9',
    messagingSenderId: '481115480812',
    projectId: 'mycotes',
    storageBucket: 'mycotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV0jZhXwb4IMXNTKfc85wE9t_Ajkkd0h8',
    appId: '1:481115480812:ios:1be876add2df2138997bc9',
    messagingSenderId: '481115480812',
    projectId: 'mycotes',
    storageBucket: 'mycotes.appspot.com',
    iosBundleId: 'in.uiquest.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV0jZhXwb4IMXNTKfc85wE9t_Ajkkd0h8',
    appId: '1:481115480812:ios:39c6d823dd441752997bc9',
    messagingSenderId: '481115480812',
    projectId: 'mycotes',
    storageBucket: 'mycotes.appspot.com',
    iosBundleId: 'in.uiquest.mynotes.RunnerTests',
  );
}
